pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'Dz', url: 'https://github.com/VladislavLavrov/423901_devops_SvintsovIlya.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('steel_predict_project') {
                    sh 'docker build -t steel_app .'
                }
            }
        }

        stage('Compose Up') {
            steps {
                dir('steel_predict_project') {
                    sh 'docker compose up -d --build'
                }
            }
        }

        stage('Run Migrations') {
            steps {
                dir('steel_predict_project') {
                    sh 'docker compose run web python manage.py migrate'
                }
            }
        }
    }

    post {
        failure {
            echo "Build failed"
        }
    }
}
