# Generated by Django 5.2.7 on 2025-10-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steel_type', models.CharField(choices=[('carbon', 'Углеродистая сталь'), ('stainless', 'Нержавеющая сталь')], max_length=20)),
                ('C', models.FloatField()),
                ('Mn', models.FloatField()),
                ('Si', models.FloatField()),
                ('P', models.FloatField()),
                ('S', models.FloatField()),
                ('Ni', models.FloatField(blank=True, null=True)),
                ('Cr', models.FloatField(blank=True, null=True)),
                ('Mo', models.FloatField(blank=True, null=True)),
                ('Ti', models.FloatField(blank=True, null=True)),
                ('UTS', models.FloatField()),
                ('YS', models.FloatField()),
                ('Elongation', models.FloatField()),
                ('Hardness', models.FloatField()),
                ('Reduction', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
